baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Oli Phillips'
theme = "hermit-v2"

[params]
  homeSubtitle = "just things I like."
  homeSubtitlePrinter = true

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about-hugo/"
    weight = 3